---
# tasks file for docker_rhel_install
# this role is for installing docker on RHEL Server only

- name: Install python setup tools
  yum: name=python-setuptools
  
- name: Install Pypi
  easy_install: name=pip
  
- name: Install docker-py
  pip: name=docker-py

- name: Create docker group
  group: name=docker state=present 
 
- name: Install Docker
  yum: name=docker state=latest
  
- name: Make sure Docker is running
  service: name=docker state=running

- name: enable Docker on boot
  service: name=docker enabled=yes

- name: Docker pull RHEL7.2 image
  shell: docker pull rhel7.2

- name: Docker pull RHEL7.3 image
  shell: docker pull rhel7.3
