# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export http_proxy=http://repo.alabs.datacom.co.nz:3128/
export https_proxy=http://repo.alabs.datacom.co.nz:3128/
export PATH

